image: Visual Studio 2017
platform: x64
configuration: Release

environment:
  global:
    PYTHON: "C:\\Python37-x64"
    # skip 2.7, 3.4 and 3.5: for now, only build for >= 3.6
    CIBW_SKIP: "cp27-* cp33-* cp34-* cp35-*"
    CIBW_TEST_REQUIRES: "pytest"
    CIBW_TEST_COMMAND: "cd {project} && pytest"
    TWINE_USERNAME: "anthrotype"
    TWINE_PASSWORD:
      secure: 9L/DdqoIILlN7qCh0lotvA==

branches:
  only:
    # skip PR branches, only build from master and tagged commits
    - master
    - /^v\d+\.\d+.*$/

install:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install --upgrade pip
  - pip install cibuildwheel==1.1.0

build_script:
  - cibuildwheel --output-dir wheelhouse
  - ps: >-
      if($env:APPVEYOR_REPO_TAG -eq 'true') {
        Write-Output ("Deploying " + $env:APPVEYOR_REPO_TAG_NAME + " to PyPI...")
        pip install --upgrade twine
        twine upload wheelhouse\*.whl
      } else {
        Write-Output "Not deploying as this is not a tagged commit"
      }

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
